### ISSUE TITLE
Documentation of pre()

### ISSUE THREAD

**Issue by zilinskyjan** [davidaarmstrong/damisc#2]
A really terrific set of tools, thank you @davidaarmstrong! 

Just flagging here a minor issue with documentation; things may have moved unexpectedly when the items on lines 24-29 here were generated https://github.com/davidaarmstrong/damisc/blob/master/man/pre.Rd

e.g. `pmc` surely contains the percentage of observations in the modal category of the observed data

**Comment by davidaarmstrong** [comment]
You're correct about the interpretation of `pmc` when `mod2` is `NULL`.  When you supply a model against which `mod1` will be tested (i.e., a non-null baseline model), the `pmc` is the proportion correctly predicted by the baseline model.  Thanks for pointing it out.  I'll change the documentation to be clearer.
